### ISSUE TITLE
No licence specified

### ISSUE THREAD

**Issue by carmenbianca** [OCA/oca-ci#20]
This repository has no specified licence, making it difficult to re-use. Is it possible to add a licence?

**Comment by sbidoul** [comment]
I added a MIT LICENSE in https://github.com/OCA/oca-ci/commit/ac938eb5e06171a9fa8faa9bc1363b53e6862b07. Thanks for the heads-up.

**Comment by carmenbianca** [comment]
@sbidoul Thanks a lot for the swift response!
