### ISSUE TITLE
Question : how to use odoo Enterprise modules in test with OCA tools

### ISSUE THREAD

**Issue by AungKoKoLin1997** [OCA/oca-ci#38]
Firstly, thanks for this amazing tools.
I would like to know how to add Odoo enterprise modules among available modules for testing in Github Action?
I have a private repo and the modules depend on the odoo enterprise modules. So, when I added the modules that depend on enterprise modules, CI test is failed? I found these https://github.com/OCA/oca-ci/issues/23#issuecomment-1047974215. I don't know how to approach.

**Comment by sbidoul** [comment]
There is not "offical" way to do this, but feel free to discuss solutions with the community in https://github.com/OCA/oca-ci/discussions/36.
