### ISSUE TITLE
need to re-enable workflow?

### ISSUE THREAD

**Issue by nilshamerlinck** [OCA/oca-ci#50]
Hello @sbidoul 

I believe the [daily workflow](https://github.com/OCA/oca-ci/blob/9f97731b8c025729c00e0b3cefafb462b71da06f/.github/workflows/ci.yaml#L9) to build the images is not running anymore:

![image](https://github.com/OCA/oca-ci/assets/511258/c2113ad4-f354-49a7-9996-180d0d10368a)

As a consequence oca tests are running with a slightly outdated codebase, which is blocking in some cases.

Could you help to re-enable that workflow?

Thanks! 

PS: I didn't find a way to prevent it from being disabled again after 60d of inactivity on the repo :/

**Comment by nilshamerlinck** [comment]
Hi @sbidoul the ci worklow has been disabled again :/ I created https://github.com/OCA/oca-ci/pull/76 to hopefully prevent it from being disabled ever again.

**Comment by sbidoul** [comment]
Thanks @nilshamerlinck . I re-enabled.
