### ISSUE TITLE
Odoo 17 now requires pg_trgm

### ISSUE THREAD

**Issue by sbidoul** [OCA/oca-ci#74]
As reported by @pedrobaeza in https://github.com/OCA/sale-workflow/pull/3232#issuecomment-2227842356, it seems that Odoo 17 now requires the `pg_trgm` extension to be installed. 

This requirement was introduced recently in this commit https://github.com/odoo/odoo/commit/85b2ede4ee59bf18cdbee4ef97e9da3f023887c2

@pivi-odoo as author of that commit, maybe you can say if it was intended to add `pg_trgm` as a hard dependency in 17.0?

If yes, we can likely do it in `oca_init_test_database`.

**Comment by pivi-odoo** [comment]
Thanks for reporting the issue, we are aware of it, a fix is on it's way.
`pg_trgm` is not not required.

**Comment by pedrobaeza** [comment]
Thanks, please ping when the PR is done for tracking it.

**Comment by pivi-odoo** [comment]
Fix PR for 17.0: https://github.com/odoo/odoo/pull/173101

**Comment by sbidoul** [comment]
Thanks @pivi-odoo. Closing this as there is nothing for us to do in this project.
